In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

In [8]:
# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)
print("-" * 40)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)
print("-" * 40)

x = tf.eye(3)
print(x)
print("-" * 40)

x = tf.ones((4, 3))
print(x)
print("-" * 40)

x = tf.zeros((3, 2, 5))
print(x)
print("-" * 40)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)
print("-" * 40)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
print("-" * 40)

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
----------------------------------------
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
----------------------------------------
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
----------------------------------------
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
----------------------------------------
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)
----------------------------------------
tf.Tensor(
[[0.6322787  0.21554649]
 [0.8833896  0.48080432]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[-0.1896065  -0.8515501  -1.51678658]
 [-1.33181381  0.64437473 -0.1004085 ]
 [-1.1116997   0.27874491  0.66144496]], shape=(3, 3), dtype=float64)
----------------------------------------
tf.Tensor([0 2 4 6 8], sh

In [11]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y
print(z)
print("-" * 40)

z = tf.subtract(x, y)
z = x - y
print(z)
print("-" * 40)

z = tf.divide(x, y)
z = x / y
print(z)
print("-" * 40)

z = tf.multiply(x, y)
z = x * y
print(z)
print("-" * 40)

z = tf.tensordot(x, y, axes=1)
print(z)
print("-" * 40)

z = x ** 5
print(z)
print("-" * 40)

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y
print(z)
print("-" * 40)

x = tf.random.normal((2, 2))
print(x)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
----------------------------------------
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
----------------------------------------
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
----------------------------------------
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
----------------------------------------
tf.Tensor(46, shape=(), dtype=int32)
----------------------------------------
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
----------------------------------------
tf.Tensor(
[[ 0.5376215   0.37879756]
 [-0.24871321 -0.05239388]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[-1.0985132   0.5766267 ]
 [ 0.7764178   0.50367206]], shape=(2, 2), dtype=float32)


In [13]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print("-" * 40)
print(x[1:])
print("-" * 40)
print(x[1:3])
print("-" * 40)
# The :: is used for slicing, and the number 2 indicates the step size.
print(x[::2])
print("-" * 40)
# The :: is used for slicing, and the -1 as the step size indicates that the slice should be taken in reverse order.
print(x[::-1])
print("-" * 40)

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)
print(x_indices)
print("-" * 40)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print("-" * 40)

print(x[0:2, :])


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
----------------------------------------
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
----------------------------------------
tf.Tensor([1 1], shape=(2,), dtype=int32)
----------------------------------------
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
----------------------------------------
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
----------------------------------------
tf.Tensor([0 2], shape=(2,), dtype=int32)
----------------------------------------
tf.Tensor([1 2], shape=(2,), dtype=int32)
----------------------------------------
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [15]:
# Reshaping
x = tf.range(9)
print(x)
print("-" * 40)

x = tf.reshape(x, (3, 3))
print(x)
print("-" * 40)

x = tf.transpose(x, perm=[1, 0])
print(x)
print("-" * 40)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
----------------------------------------
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
----------------------------------------
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
----------------------------------------
